/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WifiRouteImport } from './routes/wifi'
import { Route as PrimeiroAcessoRouteImport } from './routes/primeiro-acesso'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as CobrancaSlugRouteImport } from './routes/cobranca.$slug'
import { Route as AppTransacoesRouteImport } from './routes/_app.transacoes'
import { Route as AppRelatoriosRouteImport } from './routes/_app.relatorios'
import { Route as AppQuadroRouteImport } from './routes/_app.quadro'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppNovaRouteImport } from './routes/_app.nova'
import { Route as AppFixosRouteImport } from './routes/_app.fixos'
import { Route as AppCriarRouteImport } from './routes/_app.criar'
import { Route as AppCategoriasRouteImport } from './routes/_app.categorias'
import { Route as AppAuditoriaRouteImport } from './routes/_app.auditoria'
import { Route as AppAgendaRouteImport } from './routes/_app.agenda'
import { Route as AppAcertosRouteImport } from './routes/_app.acertos'
import { Route as ApiPublicHooksDailyDigestRouteImport } from './routes/api/public/hooks/daily-digest'

const WifiRoute = WifiRouteImport.update({
  id: '/wifi',
  path: '/wifi',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimeiroAcessoRoute = PrimeiroAcessoRouteImport.update({
  id: '/primeiro-acesso',
  path: '/primeiro-acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const CobrancaSlugRoute = CobrancaSlugRouteImport.update({
  id: '/cobranca/$slug',
  path: '/cobranca/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransacoesRoute = AppTransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppQuadroRoute = AppQuadroRouteImport.update({
  id: '/quadro',
  path: '/quadro',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppNovaRoute = AppNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AppRoute,
} as any)
const AppFixosRoute = AppFixosRouteImport.update({
  id: '/fixos',
  path: '/fixos',
  getParentRoute: () => AppRoute,
} as any)
const AppCriarRoute = AppCriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriasRoute = AppCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditoriaRoute = AppAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppAcertosRoute = AppAcertosRouteImport.update({
  id: '/acertos',
  path: '/acertos',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicHooksDailyDigestRoute =
  ApiPublicHooksDailyDigestRouteImport.update({
    id: '/api/public/hooks/daily-digest',
    path: '/api/public/hooks/daily-digest',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/agendar': typeof AgendarRoute
  '/login': typeof LoginRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/wifi': typeof WifiRoute
  '/acertos': typeof AppAcertosRoute
  '/agenda': typeof AppAgendaRoute
  '/auditoria': typeof AppAuditoriaRoute
  '/categorias': typeof AppCategoriasRoute
  '/criar': typeof AppCriarRoute
  '/fixos': typeof AppFixosRoute
  '/nova': typeof AppNovaRoute
  '/perfil': typeof AppPerfilRoute
  '/quadro': typeof AppQuadroRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/transacoes': typeof AppTransacoesRoute
  '/cobranca/$slug': typeof CobrancaSlugRoute
  '/api/public/hooks/daily-digest': typeof ApiPublicHooksDailyDigestRoute
}
export interface FileRoutesByTo {
  '/agendar': typeof AgendarRoute
  '/login': typeof LoginRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/wifi': typeof WifiRoute
  '/acertos': typeof AppAcertosRoute
  '/agenda': typeof AppAgendaRoute
  '/auditoria': typeof AppAuditoriaRoute
  '/categorias': typeof AppCategoriasRoute
  '/criar': typeof AppCriarRoute
  '/fixos': typeof AppFixosRoute
  '/nova': typeof AppNovaRoute
  '/perfil': typeof AppPerfilRoute
  '/quadro': typeof AppQuadroRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/transacoes': typeof AppTransacoesRoute
  '/cobranca/$slug': typeof CobrancaSlugRoute
  '/': typeof AppIndexRoute
  '/api/public/hooks/daily-digest': typeof ApiPublicHooksDailyDigestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/agendar': typeof AgendarRoute
  '/login': typeof LoginRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/wifi': typeof WifiRoute
  '/_app/acertos': typeof AppAcertosRoute
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/auditoria': typeof AppAuditoriaRoute
  '/_app/categorias': typeof AppCategoriasRoute
  '/_app/criar': typeof AppCriarRoute
  '/_app/fixos': typeof AppFixosRoute
  '/_app/nova': typeof AppNovaRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/quadro': typeof AppQuadroRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/transacoes': typeof AppTransacoesRoute
  '/cobranca/$slug': typeof CobrancaSlugRoute
  '/_app/': typeof AppIndexRoute
  '/api/public/hooks/daily-digest': typeof ApiPublicHooksDailyDigestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendar'
    | '/login'
    | '/primeiro-acesso'
    | '/wifi'
    | '/acertos'
    | '/agenda'
    | '/auditoria'
    | '/categorias'
    | '/criar'
    | '/fixos'
    | '/nova'
    | '/perfil'
    | '/quadro'
    | '/relatorios'
    | '/transacoes'
    | '/cobranca/$slug'
    | '/api/public/hooks/daily-digest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/agendar'
    | '/login'
    | '/primeiro-acesso'
    | '/wifi'
    | '/acertos'
    | '/agenda'
    | '/auditoria'
    | '/categorias'
    | '/criar'
    | '/fixos'
    | '/nova'
    | '/perfil'
    | '/quadro'
    | '/relatorios'
    | '/transacoes'
    | '/cobranca/$slug'
    | '/'
    | '/api/public/hooks/daily-digest'
  id:
    | '__root__'
    | '/_app'
    | '/agendar'
    | '/login'
    | '/primeiro-acesso'
    | '/wifi'
    | '/_app/acertos'
    | '/_app/agenda'
    | '/_app/auditoria'
    | '/_app/categorias'
    | '/_app/criar'
    | '/_app/fixos'
    | '/_app/nova'
    | '/_app/perfil'
    | '/_app/quadro'
    | '/_app/relatorios'
    | '/_app/transacoes'
    | '/cobranca/$slug'
    | '/_app/'
    | '/api/public/hooks/daily-digest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AgendarRoute: typeof AgendarRoute
  LoginRoute: typeof LoginRoute
  PrimeiroAcessoRoute: typeof PrimeiroAcessoRoute
  WifiRoute: typeof WifiRoute
  CobrancaSlugRoute: typeof CobrancaSlugRoute
  ApiPublicHooksDailyDigestRoute: typeof ApiPublicHooksDailyDigestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wifi': {
      id: '/wifi'
      path: '/wifi'
      fullPath: '/wifi'
      preLoaderRoute: typeof WifiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primeiro-acesso': {
      id: '/primeiro-acesso'
      path: '/primeiro-acesso'
      fullPath: '/primeiro-acesso'
      preLoaderRoute: typeof PrimeiroAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/cobranca/$slug': {
      id: '/cobranca/$slug'
      path: '/cobranca/$slug'
      fullPath: '/cobranca/$slug'
      preLoaderRoute: typeof CobrancaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/transacoes': {
      id: '/_app/transacoes'
      path: '/transacoes'
      fullPath: '/transacoes'
      preLoaderRoute: typeof AppTransacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quadro': {
      id: '/_app/quadro'
      path: '/quadro'
      fullPath: '/quadro'
      preLoaderRoute: typeof AppQuadroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nova': {
      id: '/_app/nova'
      path: '/nova'
      fullPath: '/nova'
      preLoaderRoute: typeof AppNovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fixos': {
      id: '/_app/fixos'
      path: '/fixos'
      fullPath: '/fixos'
      preLoaderRoute: typeof AppFixosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/criar': {
      id: '/_app/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof AppCriarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categorias': {
      id: '/_app/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AppCategoriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auditoria': {
      id: '/_app/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AppAuditoriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/acertos': {
      id: '/_app/acertos'
      path: '/acertos'
      fullPath: '/acertos'
      preLoaderRoute: typeof AppAcertosRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/hooks/daily-digest': {
      id: '/api/public/hooks/daily-digest'
      path: '/api/public/hooks/daily-digest'
      fullPath: '/api/public/hooks/daily-digest'
      preLoaderRoute: typeof ApiPublicHooksDailyDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAcertosRoute: typeof AppAcertosRoute
  AppAgendaRoute: typeof AppAgendaRoute
  AppAuditoriaRoute: typeof AppAuditoriaRoute
  AppCategoriasRoute: typeof AppCategoriasRoute
  AppCriarRoute: typeof AppCriarRoute
  AppFixosRoute: typeof AppFixosRoute
  AppNovaRoute: typeof AppNovaRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppQuadroRoute: typeof AppQuadroRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppTransacoesRoute: typeof AppTransacoesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcertosRoute: AppAcertosRoute,
  AppAgendaRoute: AppAgendaRoute,
  AppAuditoriaRoute: AppAuditoriaRoute,
  AppCategoriasRoute: AppCategoriasRoute,
  AppCriarRoute: AppCriarRoute,
  AppFixosRoute: AppFixosRoute,
  AppNovaRoute: AppNovaRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppQuadroRoute: AppQuadroRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppTransacoesRoute: AppTransacoesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AgendarRoute: AgendarRoute,
  LoginRoute: LoginRoute,
  PrimeiroAcessoRoute: PrimeiroAcessoRoute,
  WifiRoute: WifiRoute,
  CobrancaSlugRoute: CobrancaSlugRoute,
  ApiPublicHooksDailyDigestRoute: ApiPublicHooksDailyDigestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
